### PR TITLE
add support for arduino mega 1280

### PR DESCRIPTION
**Pull request by ReinoutHeeck**
These changes add support for the original 'Arduiono Mega' board that came with the atmega 1280 mcu

**Requires** PR https://github.com/Rahix/avr-hal/pull/362 to be merged,

then **BEFORE PUBLISHING** update line 21 in Cargo.toml:
```
    19 [dependencies.arduino-hal]
    20 git = "https://github.com/rahix/avr-hal"
    21 rev = "3b8f39fa2ec5e3359c7bedc33d982e75e8cc3700"
```

### CODE REVIEW

**Comment by ReinoutHeeck** [comment]
apologies, the github UI confused me... now we have two changes here:

- add support for arduino atmega 1280
- generate an on-topic README.md

**Comment by Rahix** [comment]
Hi, thanks for the contributions!

Can you split this into two PRs, one for the new board and one for the README change, please?

**Comment by ReinoutHeeck** [comment]
The split is done

**Review by Rahix — APPROVED** [review]
Thanks!

**Comment by Rahix** [comment]
Ah, and now I was too fast and merged it before even looking at the PR over in `avr-hal`... Well, all the more motivation to get the other one merged ASAP as well.

**Comment by Rahix** [comment]
Alright, this unfortunate situation is now fixed with commit 6c54aa546ee2 ("Update avr-hal revision"). :)

**Pull request merged**
