### PR TITLE
Upgrade toolchain and disable LTO

### LINKED ISSUE #10: upgrade rust-toolchain.toml to reference nightly-07-08
There is a bug in LLVM regarding MOVW being translated into a pair of 8-bit register moves which could malfunction if the register pairs overlapped.  This was discovered while troubleshooting the ST7789 crate ( https://github.com/almindor/st7789/issues/19 ) and was reported to the rust toolchain as https://github.com/rust-lang/rust/issues/98167 .  The fix appears to be part of `nightly-07-08`, and also sorted out some strange behavior in `ufmt` . 

I recommend that you give nightly-07-08 a try, and if you do not find any showstoppers then make it the default `channel` in `rust-toolchain.toml` .

### PR DESCRIPTION
**Pull request by Patryk27**
(commit messages contain rationale)

### CODE REVIEW

**Comment by Rahix** [comment]
Hey, completely missed to also leave a comment here.  As you might have noticed, I have already pulled in the toolchain update commit here and in `avr-hal`.  Thank you again for your persistent compiler work, you are bringing the AVR backend forward a great deal.

For the LTO change, I am unsure.  From my experience, a lot of programs do not compile at all without LTO as a lot of libraries aren't annotated with `#[inline]` enough.  I think even `avr-hal` might be an offender of this as it has been used with LTO almost exclusively up to now...

**Comment by Patryk27** [comment]
Fair argument about the LTO - I suggested it mostly because people relatively frequently stumble upon that issue on internet (two times on r/rust already, IIRC) and it's peculiarly nasty, since it gives those "oh no, rust avr is broken again" vibes, when it's not even AVR's codegen fault 😓 

But yeah, if from your experience disabing LTO makes things even worse, then maybe it's better to keep it enabled and focus on actually fixing the underlying issue :smile:

**Comment by Rahix** [comment]
I agree, the situation is a bit unfortunate...

I do wonder, does the workaround I posted in that issue not work for the cases where you're hitting it?

**Comment by Patryk27** [comment]
Hmm, in which issue? 👀

**Comment by Rahix** [comment]
Here: https://github.com/rust-lang/compiler-builtins/issues/347#issuecomment-706403824

**Comment by Patryk27** [comment]
Ah, I see! I haven't checked that one yet, I'll try the next time I face this error.

**Comment by Patryk27** [comment]
Lemme close this one, to keep it tidy - I'll re-open in case I find anything :-)

**Pull request closed without merging**
